adjective =input("please enter an adjective: ")
noun =input("please enter an noun: ")
verb =input("please enter a verb ending in -ed: ")
print("Your MadLib:")
print("The", adjective, noun ,verb, "over the lazy brown dog.")